"""
Plugin system for Dev Probe.
Allows modular analysis of game state through plugins.
"""
from abc import ABC, abstractmethod
from typing import Any, Dict, List, Optional
from dataclasses import dataclass


@dataclass
class PluginReport:
    """Report generated by a plugin."""
    plugin_name: str
    summary: Dict[str, Any]
    anomalies: List[Dict[str, Any]]
    recommendations: List[str]


class DevProbePlugin(ABC):
    """Base class for Dev Probe plugins."""
    
    @property
    @abstractmethod
    def name(self) -> str:
        """Return plugin name."""
        pass
    
    @abstractmethod
    def on_snapshot(self, snapshot: Dict[str, Any]) -> Optional[Dict[str, Any]]:
        """
        Called on each snapshot.
        Return data to be included in the report.
        """
        pass
    
    @abstractmethod
    def on_event(self, event: Any) -> None:
        """Called on each tracked event."""
        pass
    
    @abstractmethod
    def on_finish(self) -> PluginReport:
        """
        Called when analysis is complete.
        Return final report.
        """
        pass


class PluginManager:
    """Manages lifecycle of Dev Probe plugins."""
    
    def __init__(self):
        self.plugins: List[DevProbePlugin] = []
    
    def register(self, plugin: DevProbePlugin) -> None:
        """Register a plugin."""
        self.plugins.append(plugin)
    
    def notify_snapshot(self, snapshot: Dict[str, Any]) -> Dict[str, Dict[str, Any]]:
        """Notify all plugins of a new snapshot."""
        results = {}
        for plugin in self.plugins:
            try:
                data = plugin.on_snapshot(snapshot)
                if data:
                    results[plugin.name] = data
            except Exception as e:
                print(f"Error in plugin {plugin.name}.on_snapshot: {e}")
        return results
    
    def notify_event(self, event: Any) -> None:
        """Notify all plugins of an event."""
        for plugin in self.plugins:
            try:
                plugin.on_event(event)
            except Exception as e:
                print(f"Error in plugin {plugin.name}.on_event: {e}")
    
    def generate_reports(self) -> List[PluginReport]:
        """Generate reports from all plugins."""
        reports = []
        for plugin in self.plugins:
            try:
                report = plugin.on_finish()
                reports.append(report)
            except Exception as e:
                print(f"Error in plugin {plugin.name}.on_finish: {e}")
        return reports
    
    def clear(self) -> None:
        """Clear all plugins."""
        self.plugins.clear()
