"""agent_kit - roles, short prompts and stage routing for sub-agents and Workflow stages (logic of `qa.py prompt` and `qa.py route`; data: lua_content/agent_kit.lua).

Shared context lives in repo files (docs/agent_context/*.md); a prompt only points at them and states TASK / SCOPE / DONE WHEN, so an Agent call costs about 150
tokens of typing instead of a re-typed CONTEXT block. The same data renders the generated `.claude/agents/*.md` and is validated by `qa.py route --check`.
"""
from __future__ import annotations

import json
import math
import re
import subprocess
import sys
import time
from pathlib import Path

import lua_bridge
import qa_report as R
from probe_settings import ROOT, qa_settings

LUA = "lua_content/agent_kit.lua"
GENERATED = "Generated by `python tools/qa.py route --write-agents`"     # first words of every generated agent file: tells ours from hand-written ones
PLACEHOLDER = re.compile(r"<(\w+)>")
QA_CMD = re.compile(r"(?:tools/|`)qa\.py\s+([a-z][\w-]*)")             # `qa.py X` in backticks or `tools/qa.py X`; prose such as "qa.py header lines" is not a command
BUDGET = re.compile(r"TURN BUDGET:\s*(\d+)")
USER_KEYS = ("task", "scope", "done")                                    # the placeholders only `qa.py prompt` can fill


# ---------------------------------------------------------------- data

def load(root: Path = ROOT) -> dict:
    return lua_bridge.load(root / LUA)


def roles(cfg: dict) -> dict:
    return {r["name"]: r for r in cfg["roles"]}


def routes(cfg: dict) -> dict:
    return {r["stage"]: r for r in cfg["routes"]}


def as_num(x) -> float:
    """A Lua number (int or float) or 0 for anything else, so a bad value is reported as 'not > 0' instead of raising."""
    return float(x) if isinstance(x, (int, float)) and not isinstance(x, bool) else 0.0


def hard_turns(cfg: dict, role: dict) -> int:
    return math.ceil(round(as_num(role["max_calls"]) * as_num(cfg["hard_turns_factor"]), 6))


def report_lines(cfg: dict, role: dict) -> list[str]:
    extra = role.get("report_extra")
    return [*([extra] if extra else []), *cfg["report"]["lines"]]


def fill(template: str, values: dict) -> str:
    """<name> placeholders, one pass (a value is never scanned again, so a task text containing `<x>` stays as typed)."""
    return PLACEHOLDER.sub(lambda m: str(values[m.group(1)]) if m.group(1) in values else _unknown(m.group(1)), template)


def _unknown(name: str) -> str:
    raise KeyError(f"unknown placeholder <{name}>")


def role_file(cfg: dict, name: str) -> str:
    return f"{cfg['context_dir']}/{name}.md"


def role_values(cfg: dict, role: dict) -> dict:
    values = {"preamble": cfg["preamble"], "role": role["name"], "role_file": role_file(cfg, role["name"]), "max_calls": role["max_calls"],
              "hard_turns": hard_turns(cfg, role), "handoff": cfg["handoff"], "max_words": cfg["report"]["max_words"],
              "lines": ", ".join(report_lines(cfg, role)), "model": role["model"], "effort": role["effort"], "tools": role["tools"]}
    return {**values, "report": fill(cfg["report"]["text"], values)}


def tokens(cfg: dict, text: str) -> int:
    return math.ceil(len(text) / as_num(cfg["chars_per_token"]))


# ---------------------------------------------------------------- rendering

def render_prompt(cfg: dict, role: dict, task: str, files=(), done: str = "") -> str:
    scope = ", ".join(files) if files else cfg["scope_default"]["write" if role["writes"] else "readonly"]
    values = {**role_values(cfg, role), "task": task.strip(), "scope": scope, "done": (done or "").strip() or role["done"]}
    return "\n".join(fill(line, values) for line in cfg["prompt"])


def render_workflow(cfg: dict, role: dict) -> str:
    values = role_values(cfg, role)
    return "\n".join(fill(line, values) for line in cfg["workflow"])


def with_pack(cfg: dict, text: str, pack: str) -> str:
    return f"{text}\n{cfg['pack_heading']}\n{pack.strip()}" if pack.strip() else text


def pack_available(root: Path = ROOT) -> bool:
    """`qa.py pack` exists once tools/qa_plugins/pack.py does (roadmap step 5); before that `prompt --pack` skips it silently."""
    return (root / "tools" / "qa_plugins" / "pack.py").is_file()


def pack_text(task: str, root: Path = ROOT, run=subprocess.run, timeout: float = 90) -> str:
    if not pack_available(root):
        return ""
    try:
        done = run([sys.executable, str(root / "tools" / "qa.py"), "pack", task], capture_output=True, text=True, encoding="utf-8", timeout=timeout, cwd=str(root))
    except (OSError, subprocess.SubprocessError):
        return ""
    return done.stdout if done.returncode == 0 else ""


# ---------------------------------------------------------------- .claude/agents/*.md (generated)

def agent_text(cfg: dict, role: dict) -> str:
    values = role_values(cfg, role)
    front = ["---", f"name: {role['name']}", f"description: {json.dumps(role['description'], ensure_ascii=False)}", f"tools: {role['tools']}",
             f"model: {role['model']}", f"effort: {role['effort']}", f"maxTurns: {values['hard_turns']}", "---"]
    return "\n".join([*front, *(fill(line, values) for line in cfg["agent_body"])]) + "\n"


def agent_files(cfg: dict, root: Path = ROOT) -> dict:
    return {root / cfg["agents_dir"] / f"{r['name']}.md": agent_text(cfg, r) for r in cfg["roles"]}


def _read(path: Path) -> str:
    return path.read_text(encoding="utf-8").replace("\r\n", "\n")


def stale_agents(cfg: dict, root: Path = ROOT) -> list[str]:
    """What differs between lua_content/agent_kit.lua and .claude/agents/: missing, edited by hand, or generated for a role that is gone."""
    want, out = agent_files(cfg, root), []
    for path, text in want.items():
        rel = path.relative_to(root).as_posix()
        if not path.is_file():
            out.append(f"{rel} is missing")
        elif _read(path) != text:
            out.append(f"{rel} differs from {LUA}")
    folder = root / cfg["agents_dir"]
    extra = [p for p in sorted(folder.glob("*.md")) if p not in want and GENERATED in _read(p)] if folder.is_dir() else []
    return out + [f"{p.relative_to(root).as_posix()} was generated for a role that no longer exists" for p in extra]


def write_agents(cfg: dict, root: Path = ROOT) -> list[str]:
    """(Re)write the generated agent files that differ; returns their paths relative to the repo root."""
    written = []
    for path, text in agent_files(cfg, root).items():
        if path.is_file() and _read(path) == text:
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8", newline="\n")
        written.append(path.relative_to(root).as_posix())
    return written


# ---------------------------------------------------------------- validation (`qa.py route --check`)

def _one_line(where: str, key: str, row: dict) -> list[str]:
    val = row.get(key)
    return [] if isinstance(val, str) and val.strip() and "\n" not in val else [f"{where}: `{key}` must be one non-empty line"]


def _tuning_problems(cfg: dict, where: str, row: dict) -> list[str]:
    out = []
    for key, allowed in (("model", cfg["models"]), ("effort", cfg["efforts"])):
        if row.get(key) not in allowed:
            out.append(f"{where}: {key} {row.get(key)!r} is not one of {', '.join(allowed)}")
    if as_num(row.get("max_calls")) <= 0:
        out.append(f"{where}: max_calls must be > 0 (got {row.get('max_calls')!r})")
    if row.get("escalate") is not None and row["escalate"] not in cfg["models"]:
        out.append(f"{where}: escalate {row['escalate']!r} is not one of {', '.join(cfg['models'])}")
    return out


def _role_file_problems(cfg: dict, role: dict, root: Path) -> list[str]:
    rel = role_file(cfg, role["name"])
    path = root / rel
    if not path.is_file():
        return [f"role {role['name']}: {rel} is missing"]
    text = path.read_text(encoding="utf-8")
    out = []
    if len(text.splitlines()) > as_num(cfg["max_role_lines"]):
        out.append(f"{rel}: {len(text.splitlines())} lines > max_role_lines={cfg['max_role_lines']}")
    budget = BUDGET.search(text)
    if not budget or int(budget.group(1)) != role["max_calls"]:
        out.append(f"{rel}: `TURN BUDGET: N` must equal max_calls={role['max_calls']} (found {budget.group(1) if budget else 'none'})")
    out += [f"{rel}: report line `{ln}` is missing" for ln in report_lines(cfg, role) if not re.search(rf"^{re.escape(ln)}", text, re.MULTILINE)]
    return out + ([] if "HOOK relay" in text else [f"{rel}: the `HOOK relay` marker (roadmap step 4) is missing"])


def role_problems(cfg: dict, role: dict, root: Path) -> list[str]:
    where = f"role {role.get('name')}"
    out = _tuning_problems(cfg, where, role)
    for key in ("name", "description", "tools", "done"):
        out += _one_line(where, key, role)
    if not isinstance(role.get("writes"), bool):
        out.append(f"{where}: writes must be true or false")
    return out + _role_file_problems(cfg, role, root)


def route_problems(cfg: dict, route: dict) -> list[str]:
    where = f"route {route.get('stage')}"
    out = _tuning_problems(cfg, where, route) + _one_line(where, "stage", route) + _one_line(where, "why", route)
    return out if route.get("role") in roles(cfg) else [*out, f"{where}: role {route.get('role')!r} is not a role"]


def _duplicates(rows: list, key: str, what: str) -> list[str]:
    seen = [r.get(key) for r in rows]
    return [f"{what} {v!r} is listed twice" for v in sorted({v for v in seen if seen.count(v) > 1}, key=str)]


def _global_problems(cfg: dict, root: Path) -> list[str]:
    out = [f"{key} must be > 0" for key in ("chars_per_token", "max_prompt_tokens", "max_role_lines") if as_num(cfg.get(key)) <= 0]
    out += ["hard_turns_factor must be >= 1 (the agent needs room to write its handoff)"] if as_num(cfg.get("hard_turns_factor")) < 1 else []
    out += [f"{cfg['preamble']} is missing"] if not (root / cfg["preamble"]).is_file() else []
    out += [] if cfg["agent_body"][0].startswith(GENERATED) else [f"agent_body[1] must start with {GENERATED!r} (how stale files are recognised)"]
    return out + _duplicates(cfg["roles"], "name", "role") + _duplicates(cfg["routes"], "stage", "stage")


def template_problems(cfg: dict) -> list[str]:
    """Unknown placeholders, and a template so long that TASK / SCOPE / DONE WHEN no longer fit under max_prompt_tokens."""
    role = cfg["roles"][0]
    known = set(role_values(cfg, role))
    groups = (("prompt", cfg["prompt"], known | set(USER_KEYS)), ("workflow", cfg["workflow"], known), ("agent_body", cfg["agent_body"], known),
              ("report.text", [cfg["report"]["text"]], known))
    out = [f"{name}: unknown placeholder <{p}>" for name, lines, ok in groups for p in sorted({p for ln in lines for p in PLACEHOLDER.findall(ln)} - ok)]
    if out:
        return out
    room = as_num(cfg["max_prompt_tokens"]) - as_num(cfg["min_task_tokens"])
    return [f"the {r['name']} prompt template alone is {tokens(cfg, render_prompt(cfg, r, ''))} tokens > {room:g} (max_prompt_tokens - min_task_tokens)"
            for r in cfg["roles"] if tokens(cfg, render_prompt(cfg, r, "")) > room]


def known_commands(root: Path = ROOT) -> set[str]:
    import tool_registry as TR
    return {t.id for t in TR.harvest_qa(root)}


def command_problems(cfg: dict, root: Path, known: set | None = None) -> tuple[list[str], list[str]]:
    """(fails, warns): a `qa.py WORD` in the agent context that is not a subcommand (unless `planned`), and a `planned` word that exists now."""
    known = known_commands(root) if known is None else known
    planned = set(cfg.get("planned") or [])
    files = [root / cfg["preamble"], *(root / role_file(cfg, n) for n in roles(cfg))]
    texts = [p.read_text(encoding="utf-8") for p in files if p.is_file()]
    texts += [*cfg["prompt"], *cfg["workflow"], *cfg["agent_body"], cfg["handoff"], cfg["report"]["text"]]
    used = {c for t in texts for c in QA_CMD.findall(t)}
    fails = [f"`qa.py {c}` is named in the agent context but is not a subcommand (coming soon? add it to `planned`)" for c in sorted(used - known - planned)]
    return fails, [f"`qa.py {c}` exists now: drop it from `planned` (and from the 'once it exists' phrases)" for c in sorted(planned & known)]


def validate(cfg: dict, root: Path = ROOT, known: set | None = None) -> tuple[list[str], list[str]]:
    """(fails, warns) of the whole kit: data, role files, templates, command names, freshness of .claude/agents/."""
    try:
        return _validate(cfg, root, known)
    except (KeyError, TypeError, IndexError, AttributeError) as exc:                # a missing key or a wrong type in the Lua data
        return [f"{LUA} is malformed: {type(exc).__name__}: {exc}"], []


def _validate(cfg: dict, root: Path, known: set | None) -> tuple[list[str], list[str]]:
    fails = _global_problems(cfg, root)
    for role in cfg["roles"]:
        fails += role_problems(cfg, role, root)
    for route in cfg["routes"]:
        fails += route_problems(cfg, route)
    if fails:
        return fails, []
    fails += template_problems(cfg)
    more, warns = command_problems(cfg, root, known)
    return fails + more + [f"stale: {s} (run `python tools/qa.py route --write-agents`)" for s in stale_agents(cfg, root)], warns


# ---------------------------------------------------------------- output (the one qa_report line)

def status_line(name: str, status: str, metrics: dict, detail: list | None = None, t0: float | None = None, repro: str | None = None) -> str:
    dur = 0.0 if t0 is None else time.perf_counter() - t0
    res = R.Result(status, metrics, detail or [], repro=repro, dur=dur, name=name)
    return R.format_line(res, len(name), None, R.report_cfg(qa_settings()))
